# Generated by Django 5.0.4 on 2024-05-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupappointment',
            name='name',
            field=models.CharField(default='Командная тренировка', max_length=128),
        ),
    ]
