# Generated by Django 5.0.4 on 2024-04-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre_id',
            field=models.IntegerField(default=0),
        ),
    ]
