# Generated by Django 5.0.4 on 2024-05-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_likes_training_plan_remove_likes_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
