# Generated by Django 5.0.4 on 2024-04-25 08:11

import gridfs_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(storage=gridfs_storage.storage.GridFSStorage(base_url='/myfiles/', collection='myfiles'), upload_to='albums')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
