# Generated by Django 5.0.4 on 2024-04-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_imagealbum_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='picture',
        ),
    ]
