# Generated by Django 5.0.4 on 2024-04-25 21:13

import gridfs_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_imagealbum_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='image',
            field=models.ImageField(default=None, storage=gridfs_storage.storage.GridFSStorage(location='albums/images'), upload_to=''),
        ),
    ]
