# Generated by Django 5.0.4 on 2024-04-25 23:32

import gridfs_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_imagealbum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='image',
            field=models.ImageField(default=None, storage=gridfs_storage.storage.GridFSStorage(location='albums/'), upload_to='images'),
        ),
    ]
