# Generated by Django 5.0.4 on 2024-04-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_imagealbum_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
