# Generated by Django 5.0.4 on 2024-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_imagealbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture_id',
            field=models.CharField(max_length=100),
        ),
    ]
