# Generated by Django 5.0.4 on 2024-04-28 17:18

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('/usr/src/app/media')),
        ),
    ]
